services:
  postgres:
    image: postgres:17.5
    container_name: rre-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rreuser
      POSTGRES_PASSWORD: rrepassword
      POSTGRES_DB: rre
    volumes:
      - ./pgdata:/var/lib/postgresql/data
